### ISSUE TITLE
Bot Skipping Welcome Messages and Inbox Protection

### ISSUE THREAD

**Issue by NamasteIndia** [rekcah-pavi/javes#1]
The bot keeps skipping welcome messages and inbox auto reply messages please fix.

**Comment by paviththanan-magicktech** [comment]
hey, first delete old welcome message by !rmwelcome before active another welcome message, and you need to set BOTLOG_CHATID  in heroku var for wlcome people with gif/sticker/big messages

and if you didnt like auto replay in pm messages you can off it by 
!set var PM_PROTECTOR False
