### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ShivamPatel2552003** [rekcah-pavi/javes#10]
**bug**
after adding ocr api key it shoud read text from picture which i reply but  it tells
Javes : Couldn't read it.
Is api key entered correct?

i tried a python progran to read ocr with my api key  and it read successfully
also please explain how to add virus total api key i wrote
VIRUS_TOTAL_API_KEY
and than added my api key
but  it tells
Failed to connect virus total , is api key added? type !help virus_scan for more info

also i tried using  VIRUSTOTAL_API_KEY
but same error
 in !goss command  it tells 
{"success":false,"error":{"code":210,"type":"invalid_url","info":"You have specified an invalid URL. Please try again or refer to the API documentation available at https:\/\/scrapestack.com\/documentation."}}

for every link
!search dont work

**Expected behavior**
to read text from picture
and scan a file using !scan command
Takes a screenshot of a website and sends the screenshot
**Python Version**
3.8.5

**Comment by rekcah-pavi** [comment]
!read <langcode>
Ex: !read eng 

VTOTAL_API - add your apikey in heroku var

!search command for public groups only

!goss command issue will be fixed soon

**Comment by ShivamPatel2552003** [comment]
Thankyou
