### ISSUE TITLE
Requirement error

### ISSUE THREAD

**Issue by himanshuadwan** [rekcah-pavi/javes#16]
Collecting bash
  Downloading bash-0.6.tar.gz (2.8 kB)
ERROR: Could not find a version that satisfies the requirement var (from -r requirements.txt (line 13)) (from versions: none)
ERROR: No matching distribution found for var (from -r requirements.txt (line 13))
The command '/bin/sh -c python3 -m pip install --no-warn-script-location --no-cache-dir --upgrade -r requirements.txt' returned a non-zero code: 1

**Comment by paviththanan-magicktech** [comment]
fixed try agin!
